import numpy as np

class PliStruct:
    # constructor
    def __init__(self):
        # String : unique identifier of  this PliStruct
        self.ID = None
        # String : structure identifier from PDBe database, ex. '1BNY'
        self.PDB = None
        # String : absolute path to the pdb file for the receptor, including flexible and rigid parts
        self.receptor = None
        # String : absolute path to the pdb file for ligand
        self.ligand = None
        # String : absolute path to the SVG  file of protein ligand interaction, generated by PoseView. May be null
        self.poseview = None 
        
        # computed with ODDT framework
        self.fingerprint = None #np.array(None)
        self.fingerprintSPLIF = None
        self.hbond = None #np.array(None)
        self.halogen = None
        self.salt = None
        self.hydrophobic = None
        self.stacking = None

        
        
    def add_trick(self, trick):
        self.tricks.append(trick)
        
